/**
 * Renders the app grid from window.APPS_CATALOG (generated by generate-apps.ps1).
 */
(function () {
  var grid = document.getElementById("appsGrid");
  var statusEl = document.getElementById("appsStatus");
  var selectEl = document.getElementById("select");
  var currentLink = "";

  if (!grid) return;

  function setStatus(message, isError) {
    if (!statusEl) return;
    statusEl.textContent = message || "";
    statusEl.hidden = !message;
    statusEl.classList.toggle("is-error", !!isError);
  }

  function createCard(app) {
    var card = document.createElement("a");
    card.className = "app-card";
    card.href = app.href;

    if (typeof app.modes === "number") {
      card.addEventListener("click", function (e) {
        e.preventDefault();
        e.stopPropagation();
        openDialogue(app, e);
      });
    }

    var media = document.createElement("div");
    media.className = "app-card__media";

    var img = document.createElement("img");
    img.src = app.image || "./Assets/Images/testapp.png";
    img.alt = app.title || app.id || "App";
    img.loading = "lazy";
    img.onerror = function () {
      this.onerror = null;
      this.src = "./Assets/Images/testapp.png";
    };
    media.appendChild(img);

    var body = document.createElement("div");
    body.className = "app-card__body";

    var title = document.createElement("div");
    title.className = "app-card__title";
    title.textContent = app.title || app.id;
    body.appendChild(title);

    if (app.extras && app.extras.length) {
      var extras = document.createElement("div");
      extras.className = "app-card__extras";
      app.extras.forEach(function (extra) {
        var link = document.createElement("a");
        link.href = extra.href;
        link.target = "_blank";
        link.rel = "noopener noreferrer";
        link.className = "app-card__extra";
        link.title = extra.label || "Extra";
        link.addEventListener("click", function (e) {
          e.stopPropagation();
        });
        if (extra.icon) {
          var icon = document.createElement("img");
          icon.src = extra.icon;
          icon.alt = extra.label || "";
          link.appendChild(icon);
        } else {
          link.textContent = extra.label || "Link";
        }
        extras.appendChild(link);
      });
      body.appendChild(extras);
    }

    card.appendChild(media);
    card.appendChild(body);
    return card;
  }

  function openDialogue(app, event) {
    if (!selectEl) {
      location.href = app.href;
      return;
    }
    currentLink = app.href;
    var szene = document.getElementById("szene");
    if (szene) {
      szene.setAttribute("max", String(app.modes));
      szene.value = "0";
    }
    selectEl.style.visibility = "visible";
    selectEl.style.top = Math.min(event.clientY, window.innerHeight - 120) + "px";
    selectEl.style.left = Math.min(event.clientX, window.innerWidth - 220) + "px";
  }

  window.openLink = function () {
    var szene = document.getElementById("szene");
    var s = szene ? szene.value : "0";
    var link = currentLink;
    if (link.indexOf("?") >= 0) {
      link += s;
    } else {
      link += "?" + s;
    }
    location.href = link;
  };

  document.body.addEventListener("click", function (event) {
    var target = event.target;
    var className = target && target.className;
    var classStr = typeof className === "string" ? className : "";
    if (selectEl && !classStr.includes("ui") && !classStr.includes("app-card")) {
      selectEl.style.visibility = "hidden";
    }
  });

  function render(data) {
    var apps = (data && data.apps) || [];
    grid.innerHTML = "";
    if (!apps.length) {
      setStatus("Keine Apps gefunden. Bitte generate-apps.ps1 ausführen.", true);
      return;
    }
    apps.forEach(function (app) {
      grid.appendChild(createCard(app));
    });
    setStatus(apps.length + " Applikationen");
  }

  if (window.APPS_CATALOG && window.APPS_CATALOG.apps) {
    render(window.APPS_CATALOG);
    return;
  }

  setStatus("Apps werden geladen…");
  fetch("./apps.json", { cache: "no-store" })
    .then(function (res) {
      if (!res.ok) throw new Error("apps.json nicht gefunden (" + res.status + ")");
      return res.json();
    })
    .then(render)
    .catch(function (err) {
      console.error(err);
      setStatus(
        "Katalog konnte nicht geladen werden. Bitte generate-apps.ps1 ausführen.",
        true
      );
    });
})();
