var IWM = IWM || {}
IWM.conditionconfig = {
    conditionid: "show_de",
    title: "show_de",
    description: "Eine demo01-Bedingung zur Präsentation der Versuchsumgebung IWMStudy.",
    language: "DE",
    progressmaxpagecount: null,
    pagedefaults: {
        backallowed: true,
        backlabel: "zurück",
        controlsvisible: true,
        dataseparation: false,
        initdelay: 0,
        keyboardnextkeycode: null,
        layout: "iwmgrey_flex",
        loggingmedia: true,
        maxtimelabel: "Zeitlimit: ",
        mintimelabel: "Mindestzeit: ",
        nextallowed: true,
        nextlabel: "weiter",
        reloaddata: true
    },
    pages: [
        { pageid: "start", src: "show_de/start.html", nextid: "ueberblick", firstpage: true },
        { pageid: "ueberblick", src: "show_de/ueberblick.html", nextid: "einsatz", layout: "iwmgrey_flex_2cols" },
        { pageid: "einsatz", src: "show_de/einsatz.html", nextid: "studienbeginn", layout: "iwmgrey_flex_2cols" },
        { pageid: "studienbeginn", src: "show_de/studienbeginn.html", nextid: "material", layout: "iwmgrey_flex_2cols" },
        
        { pageid: "material", src: "show_de/material.html", nextid: "fragen", layout: "iwmgrey_flex_2cols" },        
        { pageid: "audio", src: "examples/audio.html", nextid: "material" },
        { pageid: "code", src: "examples/code.html", nextid: "material" },
        { pageid: "custom", src: "examples/custom.html", nextid: "material" },
        { pageid: "heading", src: "examples/heading.html", nextid: "material" },
        { pageid: "image", src: "examples/image.html", nextid: "material" },
        { pageid: "orderedlist", src: "examples/orderedlist.html", nextid: "material" },
        { pageid: "spacer", src: "examples/spacer.html", nextid: "material" },
        { pageid: "table", src: "examples/table.html", nextid: "material" },
        { pageid: "text", src: "examples/text.html", nextid: "material" },
        { pageid: "unorderedlist", src: "examples/unorderedlist.html", nextid: "material" },
        { pageid: "video", src: "examples/video.html", nextid: "material" },
        { pageid: "internallink", src: "examples/internallink.html", nextid: "material" },
        { pageid: "externallink", src: "examples/externallink.html", nextid: "material" },
        
        { pageid: "fragen", src: "show_de/fragen.html", nextid: "materialerstellung_iwmauthor", layout: "iwmgrey_flex_2cols" },
        { pageid: "question_accept", src: "examples/question_accept.html", nextid: "fragen" },
        { pageid: "question_dropdown", src: "examples/question_dropdown.html", nextid: "fragen" },
        { pageid: "question_general", src: "examples/question_general.html", nextid: "fragen" },
        { pageid: "question_multilinetext", src: "examples/question_multilinetext.html", nextid: "fragen" },
        { pageid: "question_multiplechoice", src: "examples/question_multiplechoice.html", nextid: "fragen" },
        { pageid: "question_multiscale", src: "examples/question_multiscale.html", nextid: "fragen" },
        { pageid: "question_number", src: "examples/question_number.html", nextid: "fragen" },
        { pageid: "question_scale", src: "examples/question_scale.html", nextid: "fragen" },
        { pageid: "question_singlechoice", src: "examples/question_singlechoice.html", nextid: "fragen" },
        { pageid: "question_singlelinetext", src: "examples/question_singlelinetext.html", nextid: "fragen" },
        { pageid: "question_slider", src: "examples/question_slider.html", nextid: "fragen" },
        { pageid: "question_dndcloze", src: "examples/question_dndcloze.html", nextid: "fragen" },
        { pageid: "question_dndimg2img", src: "examples/question_dndimg2img.html", nextid: "fragen" },
        { pageid: "question_dndimg2txt", src: "examples/question_dndimg2txt.html", nextid: "fragen" },
        { pageid: "question_dndimgs2img", src: "examples/question_dndimgs2img.html", nextid: "fragen" },
        { pageid: "question_dndlabeling", src: "examples/question_dndlabeling.html", nextid: "fragen" },
        { pageid: "question_dndtxt2img", src: "examples/question_dndtxt2img.html", nextid: "fragen" },
        { pageid: "question_dndtxt2txt", src: "examples/question_dndtxt2txt.html", nextid: "fragen" },
        { pageid: "question_selectcloze", src: "examples/question_selectcloze.html", nextid: "fragen" },
        
        { pageid: "materialerstellung_iwmauthor", src: "show_de/materialerstellung_iwmauthor.html", nextid: "material_interaktiv" },
        { pageid: "dateien", src: "show_de/dateien.html", nextid: "materialerstellung_iwmauthor" },
        { pageid: "konfiguration_bedingung", src: "show_de/konfiguration_bedingung.html", nextid: "dateien" },
        { pageid: "konfiguration_studie", src: "show_de/konfiguration_studie.html", nextid: "dateien" },        
        { pageid: "materialerstellung_code", src: "show_de/materialerstellung_code.html", nextid: "material_funktionen" },
        { pageid: "material_funktionen", src: "show_de/material_funktionen.html", nextid: "dateien" },

        { pageid: "material_interaktiv", src: "show_de/zeichnen_ellipsen.html", nextid: "layouts" },
        { pageid: "layouts", src: "show_de/layouts.html", nextid: "whatsapp", advpage: true, layout: "handheld_flex" },
        { pageid: "whatsapp", src: "show_de/whatsapp.html", nextid: "ablauf", layout: "whatsapp" },

        { pageid: "ablauf", src: "show_de/ablauf.html", nextid: "management", mintime: 10, maxtime: 3600 },
        { pageid: "ablauf_zufalla", src: "show_de/ablauf_zufalla.html", nextid: "ablauf_zufalla*ablauf_zufallb" },
        { pageid: "ablauf_zufallb", src: "show_de/ablauf_zufallb.html", nextid: "ablauf_zufalla*ablauf_zufallb" },
        { pageid: "ablauf_eingabe1", src: "show_de/ablauf_eingabe1.html", nextid: "ablauf", onlydata: "self.ablauf.beispieleingabe==1" },
        { pageid: "ablauf_eingabe2", src: "show_de/ablauf_eingabe2.html", nextid: "ablauf" },
        { pageid: "ablauf_maxvisits", src: "show_de/ablauf_maxvisits.html", nextid: "ablauf", maxvisits: 3 },
        { pageid: "ablauf_maxvisitserreicht", src: "show_de/ablauf_maxvisitserreicht.html", nextid: "ablauf" },
        { pageid: "ablauf_gruppe1s1", src: "show_de/ablauf_gruppe1s1.html", nextid: "ablauf_gruppe1s2", pagegroup: "group1" },
        { pageid: "ablauf_gruppe1s2", src: "show_de/ablauf_gruppe1s2.html", nextid: "ablauf", pagegroup: "group1" },

        { pageid: "management", src: "show_de/management.html", nextid: "logdateien" },
        { pageid: "logdateien", src: "show_de/logdateien.html", nextid: "anonymousdata" },        
        { pageid: "anonymousdata", src: "show_de/anonymousdata.html", nextid: "multiuser" },
        { pageid: "multiuser", src: "show_de/multiuser.html", nextid: "projekt" },
        { pageid: "projekt", src: "show_de/projekt.html", nextid: "ende" },
        { pageid: "ende", src: "show_de/ende.html", nextallowed: false, lastpage: true }
    ],
    pagegroups: [
        { pagegroupid: "group1", maxtime: 60 }        
    ]
}
